### ISSUE TITLE
Make http://caco3.me have HTTPS

### ISSUE THREAD

**Issue by ImNimboss** [Calciumcarbonate321/Calciumcarbonate321.github.io#1]
I'm not too sure how GitHub Pages custom domain settings work but I think there's an option to change an http custom domain to https right? https://caco3.me would hold a lot more trust to viewers than http://caco3.me , because the stereotype goes "http = sketchy website"

**Comment by ImNimboss** [comment]
Oh wait I was visiting the wrong domain, you do have https

**Comment by Calciumcarbonate321** [comment]
Lol
